import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser' });
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
const errs = []; p.on('pageerror', (e) => errs.push(String(e))); p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto('file://' + process.cwd() + '/anim-dist/index.html');
await p.waitForTimeout(1200);
const sc = await p.evaluate(() => window.__scenes());
const s12 = sc[12];
// the first stop of Tutorial 3 Q2 is at intro 9 + 7 - 0.4 = 15.6 s into the scene
await p.evaluate((t) => window.__seek(t), s12.off + 14.5);
await p.click('#play');
await p.waitForTimeout(2200);
const on = await p.$eval('.try', (e) => e.classList.contains('on'));
const prompt = await p.$eval('.try .p', (e) => e.textContent);
console.log('stop opened:', on, '|', prompt.slice(0, 60));
await p.fill('.try input', '1.5');
await p.click('.try button.go');
console.log('wrong ->', await p.$eval('.try .fb', (e) => e.textContent));
await p.click('text=Hint');
console.log('hint ->', await p.$eval('.try .fb', (e) => e.textContent));
await p.fill('.try input', '1.69');
await p.click('.try .row button.go');
console.log('right ->', await p.$eval('.try .fb', (e) => e.textContent));
await p.screenshot({ path: process.argv[2] + '/try.png', clip: { x: 0, y: 0, width: 1600, height: 1000 } });
await p.click('text=Continue ▶');
const t0 = await p.evaluate(() => document.querySelector('.time').textContent);
await p.waitForTimeout(1500);
const t1 = await p.evaluate(() => document.querySelector('.time').textContent);
console.log('playing after continue:', t0, '->', t1, '| overlay off:', !(await p.$eval('.try', (e) => e.classList.contains('on'))));
// a multiple-choice stop: Tutorial 4 Q2 (b) at 9 + 16 - 0.4
const s24 = sc[24];
if ((await p.textContent('#play')).includes('Pause')) await p.click('#play');
await p.evaluate((t) => window.__seek(t), s24.off + 23.5);
await p.click('#play');
await p.waitForTimeout(2200);
console.log('MCQ stop:', await p.$eval('.try', (e) => e.classList.contains('on')), (await p.$$('.try .choices button')).length, 'choices');
await p.click('.try .choices button >> nth=1');
console.log('wrong choice ->', await p.$eval('.try .fb', (e) => e.textContent));
await p.click('.try .choices button >> nth=0');
console.log('right choice ->', await p.$eval('.try .fb', (e) => e.textContent));
console.log('errors:', JSON.stringify(errs));
await b.close();
