/**
 * Global glossary: every symbol in CLAUDE.md §6, defined once, hoverable everywhere.
 * Lesson text refers to entries as {{key}}.
 */
export interface GlossaryEntry {
  tex: string;
  name: string;
  def: string;
  unit?: string;
  firstIn: string; // lesson id where it is introduced
}

export const GLOSSARY: Record<string, GlossaryEntry> = {
  VDD: { tex: 'V_{DD}', name: 'supply voltage', def: 'The positive supply rail: the top of the tank. Every node voltage is measured from ground up to it.', unit: 'V', firstIn: 'u0-drops' },
  VSS: { tex: 'V_{SS}', name: 'negative supply', def: 'The bottom rail when a circuit uses a split supply (e.g. −0.9 V).', unit: 'V', firstIn: 'u0-drops' },
  ground: { tex: '0\\,\\mathrm{V}', name: 'ground', def: 'The reference node, 0 V. Sea level in the water picture.', firstIn: 'u0-drops' },
  I: { tex: 'I', name: 'current', def: 'Flow of charge through a branch, in amperes. The same current flows through everything in series.', unit: 'A', firstIn: 'u0-drops' },
  R: { tex: 'R', name: 'resistance', def: 'How hard it is to push current through: V = I·R. A narrow pipe.', unit: 'Ω', firstIn: 'u0-drops' },
  par: { tex: 'R_1 \\parallel R_2', name: 'parallel', def: 'Two resistors across the same two nodes: R1R2/(R1 + R2). Always smaller than either; the smallest resistance wins.', firstIn: 'u0-parallel' },
  VG: { tex: 'V_G', name: 'gate voltage', def: 'Voltage of the gate node, measured from ground.', unit: 'V', firstIn: 'u1-mosfet' },
  VD: { tex: 'V_D', name: 'drain voltage', def: 'Voltage of the drain node, measured from ground.', unit: 'V', firstIn: 'u1-mosfet' },
  VS: { tex: 'V_S', name: 'source voltage', def: 'Voltage of the source node, measured from ground.', unit: 'V', firstIn: 'u1-mosfet' },
  VGS: { tex: 'V_{GS}', name: 'gate-source voltage', def: 'VG − VS: how hard the gate is pulling electrons into the channel.', unit: 'V', firstIn: 'u1-mosfet' },
  VDS: { tex: 'V_{DS}', name: 'drain-source voltage', def: 'VD − VS: the voltage that pushes electrons along the channel.', unit: 'V', firstIn: 'u1-mosfet' },
  Vth: { tex: 'V_{th}', name: 'threshold voltage', def: 'The VGS at which a channel first forms. Below it the device is off. Vthn for NMOS, |Vthp| for PMOS.', unit: 'V', firstIn: 'u1-mosfet' },
  Vov: { tex: 'V_{ov}', name: 'overdrive', def: 'Vov = VGS − Vth: how far past threshold the gate is. Sets the channel thickness. The most important number in the course.', unit: 'V', firstIn: 'u1-mosfet' },
  WL: { tex: 'W/L', name: 'aspect ratio', def: 'Channel width over length: the size of the tap. You choose it when you design.', firstIn: 'u1-mosfet' },
  muCox: { tex: '\\mu_n C_{ox}', name: 'process transconductance', def: 'Mobility × oxide capacitance per area, fixed by the process (µnCox for NMOS, µpCox for PMOS). Given as one number, e.g. 200 µA/V².', unit: 'A/V²', firstIn: 'u1-mosfet' },
  ID: { tex: 'I_D', name: 'drain current', def: 'Current flowing into the drain and out of the source (NMOS).', unit: 'A', firstIn: 'u2-squarelaw' },
  lambda: { tex: '\\lambda', name: 'channel-length modulation', def: 'The small upward slope of the “flat” saturation curve. λ ∝ 1/L. Gives the device a finite rO.', unit: 'V⁻¹', firstIn: 'u2-squarelaw' },
  pinch: { tex: 'V_{DS} = V_{ov}', name: 'pinch-off', def: 'The point where the channel thickness at the drain end reaches zero. Beyond it the device is saturated.', firstIn: 'u2-pinchoff' },
  fence: { tex: 'V_D \\ge V_G - V_{th}', name: 'the saturation fence', def: 'NMOS is saturated when its drain stays above its gate minus one threshold. PMOS: VD ≤ VG + |Vth|.', firstIn: 'u2-pinchoff' },
  gm: { tex: 'g_m', name: 'transconductance', def: 'How much drain current changes per volt of gate wiggle: gm = 2ID/Vov = √(2µCox(W/L)ID) = µCox(W/L)Vov.', unit: 'S (A/V)', firstIn: 'u4-gm' },
  rO: { tex: 'r_O', name: 'output resistance', def: 'The small-signal resistance looking into the drain: rO = 1/(λID).', unit: 'Ω', firstIn: 'u4-ro' },
  gmro: { tex: 'g_m r_O', name: 'intrinsic gain', def: 'The largest gain one transistor can give: gm·rO = 2/(λVov). At a fixed overdrive it does not depend on ID.', firstIn: 'u4-ro' },
  Av: { tex: 'A_v', name: 'voltage gain', def: 'vout/vin for small signals. Negative means the stage inverts.', unit: 'V/V', firstIn: 'u5-cs' },
  Gm: { tex: 'G_m', name: 'stage transconductance', def: 'Output short-circuit current per input volt, for a whole stage.', unit: 'S', firstIn: 'u5-cs' },
  Rout: { tex: 'R_{out}', name: 'output resistance', def: 'Resistance seen looking into the output node with the input grounded.', unit: 'Ω', firstIn: 'u5-cs' },
  RS: { tex: 'R_S', name: 'source resistor', def: 'A resistor under the source (degeneration). It fights back: raises Rout (up multiplies) and lowers Gm.', unit: 'Ω', firstIn: 'u6-rules' },
  Rdown: { tex: 'R_{down}', name: 'resistance looking down', def: 'From the output node down into the NMOS stack. For a cascode ≈ gm·rO·rO.', unit: 'Ω', firstIn: 'u9-cascode' },
  Rup: { tex: 'R_{up}', name: 'resistance looking up', def: 'From the output node up into the PMOS load. rO for a simple source, ≈ gm·rO² for a cascoded one.', unit: 'Ω', firstIn: 'u9-cascode' },
  VISS: { tex: 'V_{ISS}', name: 'tail headroom', def: 'The voltage the tail current source needs across it to stay saturated (its Vov for a transistor tail). Not a supply.', unit: 'V', firstIn: 'u9-telescopic' },
  ISS: { tex: 'I_{SS}', name: 'tail current', def: 'The current of the source under a differential pair. At balance each side carries ISS/2.', unit: 'A', firstIn: 'u10-steering' },
  VCM: { tex: 'V_{CM}', name: 'common-mode voltage', def: 'The average of the two inputs, (Vin1 + Vin2)/2. The pair ignores it (within its CM range).', unit: 'V', firstIn: 'u10-steering' },
  vd: { tex: 'v_d', name: 'differential input', def: 'The difference Vin1 − Vin2. The pair amplifies this.', unit: 'V', firstIn: 'u10-steering' },
  Ad: { tex: 'A_d', name: 'differential gain', def: 'Output difference per input difference. From the DM half circuit: gm·(load).', unit: 'V/V', firstIn: 'u10-half' },
  ACM: { tex: 'A_{CM}', name: 'common-mode gain', def: 'How much an output moves when both inputs move together. Small; from the CM half circuit with 2RSS.', unit: 'V/V', firstIn: 'u10-half' },
  CL: { tex: 'C_L', name: 'load capacitance', def: 'The capacitor at the output node: it sets the dominant pole and the slew rate.', unit: 'F', firstIn: 'u12-poles' },
  omegau: { tex: '\\omega_u', name: 'unity-gain frequency (GBW)', def: 'Where the open-loop gain falls to 1. One-stage op amp: gm/CL. In Hz divide by 2π.', unit: 'rad/s', firstIn: 'u12-poles' },
  tau: { tex: '\\tau', name: 'time constant', def: 'Closed-loop settling time constant: 1/(β·ωu) = Aclosed/ωu.', unit: 's', firstIn: 'u12-settling' },
  eps: { tex: '\\varepsilon', name: 'error', def: 'The fraction still missing: gain error 1/(1 + βA), or the settling band (0.01 = 1%).', firstIn: 'u12-settling' },
  beta: { tex: '\\beta', name: 'feedback factor', def: 'The fraction of the output fed back to the input. A divider R2/(R1 + R2); 1 for a buffer.', firstIn: 'u12-settling' },
  SR: { tex: 'SR', name: 'slew rate', def: 'The fastest the output can move: SR = ISS/CL for a one-stage OTA.', unit: 'V/s', firstIn: 'u12-settling' },
  Aopen: { tex: 'A_{open}', name: 'open-loop gain', def: 'The op amp’s own gain, with no feedback. Huge but sloppy: it changes with temperature and process.', firstIn: 'l1-gain' },
  Aclosed: { tex: 'A_{closed}', name: 'closed-loop gain', def: 'The gain with feedback: A/(1 + βA) ≈ 1/β, set by resistors.', firstIn: 'l1-gain' },
  RD: { tex: 'R_D', name: 'drain resistor', def: 'Load resistor from VDD to the drain.', unit: 'Ω', firstIn: 'u3-recipe' },
  VREF: { tex: 'V_{REF}', name: 'reference voltage', def: 'The voltage the CMFB loop makes the output common mode equal to.', unit: 'V', firstIn: 'l8-replica' },
  PSRR: { tex: 'PSRR', name: 'power-supply rejection ratio', def: 'Gain from the input divided by gain from the supply to the output. 5-T OTA: ≈ gm(rOP‖rON). Quoted in dB.', firstIn: 'l10-psrr' },
  Vn: { tex: '\\overline{V_n}', name: 'input-referred noise', def: 'The noise voltage that, placed at the input of a noiseless copy, gives the same output noise. Density in V/√Hz (often nV/√Hz).', unit: 'V/√Hz', firstIn: 'l10-noise' },
  gamma: { tex: '\\gamma', name: 'noise coefficient', def: 'Thermal-noise factor of a MOSFET: its drain noise current is 4kTγgm. ≈ 2/3 for long channels.', firstIn: 'l10-noise' },
  kT: { tex: 'kT', name: 'thermal energy', def: 'Boltzmann’s constant × absolute temperature: 1.38×10⁻²³ × 300 ≈ 4.14×10⁻²¹ J at room temperature.', unit: 'J', firstIn: 'l10-noise' },
  Af: { tex: 'A_f', name: 'closed-loop gain (notes)', def: 'Your notes’ name for the closed-loop gain A/(1 + βA). Same as Aclosed.', unit: 'V/V', firstIn: 'l11-barkhausen' },
  betaA: { tex: '\\beta A', name: 'loop gain', def: 'The gain once round the loop, βA(s). Stability depends only on it: its size |βA| and its phase ∠βA.', firstIn: 'l11-barkhausen' },
  omegap1: { tex: '\\omega_{p1}', name: 'first (dominant) pole', def: 'The lowest pole of A(s): where the gain starts to fall at 20 dB/dec and the phase reaches −45°.', unit: 'rad/s', firstIn: 'l11-barkhausen' },
  omegap2: { tex: '\\omega_{p2}', name: 'second (non-dominant) pole', def: 'The next pole: the gain falls at 40 dB/dec above it and it adds up to another −90° of phase.', unit: 'rad/s', firstIn: 'l11-multipole' },
  omegagx: { tex: '\\omega_{gx}', name: 'gain crossover', def: 'The frequency where |βA| = 1 (0 dB). Where |A| meets the 20log(1/β) line.', unit: 'rad/s', firstIn: 'l11-multipole' },
  omegapx: { tex: '\\omega_{px}', name: 'phase crossover', def: 'The frequency where ∠βA = −180°.', unit: 'rad/s', firstIn: 'l11-multipole' },
  PM: { tex: 'PM', name: 'phase margin', def: 'PM = 180° + ∠βA at ωgx: how many degrees are left before oscillation. Aim for ≈ 60°.', unit: '°', firstIn: 'l12-margins' },
  GM: { tex: 'GM', name: 'gain margin', def: 'How far |βA| is below 0 dB at ωpx: GM = −20log|βA(ωpx)|.', unit: 'dB', firstIn: 'l12-margins' },
  CC: { tex: 'C_C', name: 'compensation (Miller) capacitor', def: 'The capacitor across the second stage. Seen from node 1 it is CC(1 + A2); it sets GBW = Gm1/CC and SR = ISS/CC.', unit: 'F', firstIn: 'l13-miller' },
  A2: { tex: 'A_2', name: 'second-stage gain', def: 'Gm2·R2: the gain of the output stage (M6 with M7).', unit: 'V/V', firstIn: 'l13-miller' },
  R1: { tex: 'R_1', name: 'first-stage output resistance', def: 'Resistance at node 1 (the first stage’s output, P): rO2‖rO4 in the notes’ circuit.', unit: 'Ω', firstIn: 'l13-miller' },
  C1: { tex: 'C_1', name: 'node-1 capacitance', def: 'The parasitic capacitance at the first stage’s output (the gate of M6).', unit: 'F', firstIn: 'l13-miller' },
  R2: { tex: 'R_2', name: 'output resistance of stage 2', def: 'rO6‖rO7 in the notes’ circuit.', unit: 'Ω', firstIn: 'l13-miller' },
  C2: { tex: 'C_2', name: 'output capacitance', def: 'The load at the output node (CL plus parasitics).', unit: 'F', firstIn: 'l13-miller' },
  omegaz: { tex: '\\omega_z', name: 'zero', def: 'A frequency where the transfer function goes to zero. The Miller RHP zero Gm2/CC lags the phase like a pole.', unit: 'rad/s', firstIn: 'l14-rz' },
  Rz: { tex: 'R_z', name: 'nulling resistor', def: 'Resistor in series with CC. 1/Gm2 removes the RHP zero; (CL + CC)/(Gm2CC) puts it on the second pole.', unit: 'Ω', firstIn: 'l14-rz' },
  VOH: { tex: 'V_{OH}', name: 'output high level', def: 'The output voltage when the output is a logic 1 (VDD for CMOS).', unit: 'V', firstIn: 'd15-statics' },
  VOL: { tex: 'V_{OL}', name: 'output low level', def: 'The output voltage when the output is a logic 0 (0 for CMOS; above 0 for ratioed loads).', unit: 'V', firstIn: 'd15-statics' },
  VIL: { tex: 'V_{IL}', name: 'input low threshold', def: 'The largest input still read as 0: the lower input where the VTC slope is −1.', unit: 'V', firstIn: 'd15-statics' },
  VIH: { tex: 'V_{IH}', name: 'input high threshold', def: 'The smallest input read as 1: the upper input where the VTC slope is −1.', unit: 'V', firstIn: 'd15-statics' },
  VM: { tex: 'V_M', name: 'switching threshold', def: 'The input voltage at which Vout = Vin (Kang writes Vth for it). CMOS: both devices saturated there.', unit: 'V', firstIn: 'd15-statics' },
  NM: { tex: 'NM_L,\\,NM_H', name: 'noise margins', def: 'NML = VIL − VOL and NMH = VOH − VIH: how much noise a 0 or a 1 can survive between a driver and a receiver.', unit: 'V', firstIn: 'd15-statics' },
  kR: { tex: 'k_R', name: 'size ratio', def: 'kR = kn/kp (driver over load): sets VOL of ratioed inverters and VM of a CMOS inverter.', firstIn: 'd16-loads' },
  tauPHL: { tex: '\\tau_{PHL}', name: 'high-to-low delay', def: 'From the input’s 50% point to the output’s 50% point as the output falls (the nMOS discharges CL).', unit: 's', firstIn: 'd18-switching' },
  tauPLH: { tex: '\\tau_{PLH}', name: 'low-to-high delay', def: 'The same for a rising output (the pMOS charges CL).', unit: 's', firstIn: 'd18-switching' },
  LEg: { tex: 'g', name: 'logical effort', def: 'How much more input capacitance a gate needs than an inverter to deliver the same current: inverter 1, NAND2 4/3, NOR2 5/3.', firstIn: 'd24-linear' },
  LEh: { tex: 'h', name: 'electrical effort', def: 'h = Cout/Cin: the load relative to the gate’s own input capacitance (the fan-out).', firstIn: 'd24-linear' },
  LEp: { tex: 'p', name: 'parasitic delay', def: 'The delay of a gate driving only its own drain capacitance: inverter 1, n-input NAND/NOR ≈ n (units of τ).', firstIn: 'd24-linear' },
  Fpath: { tex: 'F', name: 'path effort', def: 'F = G·B·H: product of the logical efforts, the branching efforts and the overall Cout/Cin.', firstIn: 'd25-path' },
  alpha: { tex: '\\alpha', name: 'activity factor', def: 'The probability that a node makes a 0→1 transition in a clock cycle.', firstIn: 'd26-power' },
  tpcq: { tex: 't_{pcq}', name: 'clock-to-Q delay', def: 'Time from the clock edge until the flip-flop output is valid (tccq: the earliest it can start changing).', unit: 's', firstIn: 'd31-sequencing' },
  tsetup: { tex: 't_{setup}', name: 'setup time', def: 'How long before the clock edge the input must be stable.', unit: 's', firstIn: 'd31-sequencing' },
  thold: { tex: 't_{hold}', name: 'hold time', def: 'How long after the clock edge the input must stay stable.', unit: 's', firstIn: 'd32-maxmin' },
  tskew: { tex: 't_{skew}', name: 'clock skew', def: 'The worst-case difference in arrival time of the clock at the launching and capturing elements.', unit: 's', firstIn: 'd33-skew' },
  CR: { tex: 'CR', name: 'cell ratio', def: 'SRAM: pull-down strength ÷ access strength. About 1.5–2 or more keeps a read from flipping the cell.', firstIn: 'd38-sram' },
  GP: { tex: 'G_i,\\,P_i', name: 'generate and propagate', def: 'Gi = AiBi (the column makes a carry by itself); Pi = Ai ⊕ Bi (it passes the incoming carry on). Ci+1 = Gi + PiCi.', firstIn: 'd35-fulladder' },
  PP: { tex: 'PP', name: 'partial product', def: 'One shifted copy of the multiplicand selected by (a digit of) the multiplier; the partial products are added to form the product.', firstIn: 'd37-multiplier' },
};
